const nodemailer = require("nodemailer");

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

const sendGrievanceEmail = async ({
  recipient,
  grievance,
  attachmentPath,
}) => {

  const subcatOrSubject = grievance.subcategory || grievance.subject || grievance.main_category || 'Grievance Referral';
  const refNo = grievance.reference_no || grievance.reference_number || 'N/A';
  const category = grievance.main_category || grievance.category || 'N/A';
  const subcategory = grievance.subcategory || 'General Inquiry';
  const priority = grievance.priority || 'Normal';
  const dateReceived = grievance.date_received || grievance.received_at || 'Not recorded';
  const referredTo = grievance.referred_to || grievance.assigned_division || 'Department';

  const mailOptions = {
    from: `"MWCA Grievance Management System" <${process.env.EMAIL_USER}>`,
    to: recipient,
    subject: `[MWCA Grievance Referral] ${refNo} – ${subcatOrSubject}`,
    text: [
      'Dear Sir/Madam,',
      '',
      'A grievance has been referred to your office by the Ministry of Women and Child Affairs for necessary review and action.',
      '',
      'GRIEVANCE DETAILS',
      '',
      `Reference No. : ${refNo}`,
      `Category      : ${category}`,
      `Subcategory   : ${subcategory}`,
      `Priority      : ${priority}`,
      `Date Received : ${dateReceived}`,
      `Referred To   : ${referredTo}`,
      '',
      'Summary:',
      grievance.description || 'Request for assistance regarding grievance matter.',
      '',
      'ACTION REQUIRED',
      '',
      'Kindly review the grievance and the attached documents and take the necessary action in accordance with the relevant procedures.',
      '',
      `Please quote the reference number ${refNo} in all correspondence related to this grievance.`,
      '',
      'Thank you.',
      '',
      'Grievance Management System',
      'Administration Division',
      'Ministry of Women and Child Affairs',
      '',
      '------------------------------------------------------------',
      'This is an automated notification generated by the',
      'MWCA Grievance Management System.'
    ].join('\n'),
    attachments: attachmentPath
      ? [
          {
            filename: attachmentPath.split(/[\\/]/).pop(),
            path: attachmentPath,
          },
        ]
      : [],
  };

  return await transporter.sendMail(mailOptions);
};

module.exports = {
  sendGrievanceEmail,
};